In [1]:
from corpus_methods.TimeML_corpus_reading import *
from corpus_methods.Text_object_with_layers import *
from corpus_methods.file_operations import *

In [2]:
pwd

'C:\\Users\\liivas\\Documents\\Magistritöö\\andmetootlus'

In [3]:
# töötab
#!python EstTimeMLCorpus/exported_corpus_reader.py EstTimeMLCorpus/corpus

### Creating Text-object from one example article and adding event and timex layers

In [70]:
baseAnnotations = load_base_segmentation(baseAnnotationFile)
(eventsByLoc, eventsByID) = load_entity_annotation(eventAnnotationFile)
articlesDCT = load_articles_DCT(articleMetadata_file)
sentence_events =  eventsByLoc.get('aja_ml_2002_47.tasak.a023.sol')
sentence_events =  eventsByID.get('aja_ml_2002_47.tasak.a023.sol')
(timexesByLoc, timexesByID) = load_entity_annotation(timexAnnotationFile)
sentence_timex = timexesByLoc.get('aja_ml_2002_47.tasak.a023.sol')

In [71]:
article_text, mapping = create_Text_object('aja_ml_2002_47.tasak.a023.sol', articlesDCT, baseAnnotations, 
                                           eventsByLoc, timexesByLoc)
article_text.gold_events

Layer(name='gold_events', attributes=('corpus_sentence_ID', 'corpus_word_ID', 'event_ID', 'expression', 'event_annotation', 'event_class'), spans=SL[Span('piimavarumisel', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 3, 'event_ID': 'e1', 'expression': '"piimavarumisel"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('kestnud', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 4, 'event_ID': 'e2', 'expression': '"kestnud"', 'event_annotation': 'EVENT ASPECTUAL comment="fraas: kestnud anarhia"', 'event_class': 'ASPECTUAL'}]),
Span('anarhia', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 5, 'event_ID': 'e3', 'expression': '"anarhia"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('tundubki', [{'corpus_sentence_ID': 2, 'corpus_word_ID': 2, 'event_ID': 'e4', 'expression': '"tundubki"', 'event_annotation': 'EVENT I_STATE', 'event_class': 'I_STATE'}]),
Span('hakkavad', [{'corpus_sentence_ID': 2, 'corpus_word_ID': 7, 'event_ID': 'e5', 'expression': '"hakkavad"', 'event_annotation': 'EVENT ASPECTUAL', 'event_class': 'ASPECTUAL'}]),
Span('saama', [{'corpus_sentence_ID': 2, 'corpus_word_ID': 9, 'event_ID': 'e6', 'expression': '"saama"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('tuleb', [{'corpus_sentence_ID': 2, 'corpus_word_ID': 11, 'event_ID': 'e7', 'expression': '"tuleb"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('on', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 5, 'event_ID': 'e8', 'expression': '"on võlgu"', 'event_annotation': 'EVENT STATE multiword="true"', 'event_class': 'STATE'}]),
Span('võlgu', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 9, 'event_ID': 'e8', 'expression': '"on võlgu"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('pälvis', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 11, 'event_ID': 'e9', 'expression': '"pälvis"', 'event_annotation': 'EVENT OCCURRENCE comment="ka I_STATE: see, et on võlgu, pälvis tähelepanu"', 'event_class': 'OCCURRENCE'}]),
Span('tahtis', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 19, 'event_ID': 'e10', 'expression': '"tahtis"', 'event_annotation': 'EVENT I_STATE', 'event_class': 'I_STATE'}]),
Span('teenete', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 27, 'event_ID': 'e11', 'expression': '"teenete"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('kinkida', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 30, 'event_ID': 'e12', 'expression': '"kinkida"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('võtab', [{'corpus_sentence_ID': 4, 'corpus_word_ID': 2, 'event_ID': 'e13', 'expression': '"võtab"', 'event_annotation': 'EVENT STATE comment="fraas: võtab kokku"', 'event_class': 'STATE'}]),
Span('saadetud', [{'corpus_sentence_ID': 4, 'corpus_word_ID': 8, 'event_ID': 'e14', 'expression': '"saadetud"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('kirjutasid', [{'corpus_sentence_ID': 5, 'corpus_word_ID': 1, 'event_ID': 'e15', 'expression': '"kirjutasid"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('saamata', [{'corpus_sentence_ID': 5, 'corpus_word_ID': 10, 'event_ID': 'e16', 'expression': '"saamata"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('seisab', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 1, 'event_ID': 'e17', 'expression': '"seisab"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('palume', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 6, 'event_ID': 'e18', 'expression': '"palume"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('abi', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 8, 'event_ID': 'e19', 'expression': '"abi"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('tunneks', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 15, 'event_ID': 'e20', 'expression': '"tunneks"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('oskaks', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 18, 'event_ID': 'e21', 'expression': '"oskaks"', 'event_annotation': 'EVENT I_STATE', 'event_class': 'I_STATE'}]),
Span('kaitsta', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 24, 'event_ID': 'e22', 'expression': '"kaitsta"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('saamata', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 3, 'event_ID': 'e23', 'expression': '"saamata"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('tähendab', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 5, 'event_ID': 'e24', 'expression': '"tähendab"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('pole', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 7, 'event_ID': 'e25', 'expression': '"pole vaja"', 'event_annotation': 'EVENT STATE polarity="NEG" multiword="true"', 'event_class': 'STATE'}]),
Span('vaja', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 8, 'event_ID': 'e25', 'expression': '"pole vaja"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('seletada', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 9, 'event_ID': 'e26', 'expression': '"seletada"', 'event_annotation': 'EVENT OCCURRENCE polarity="NEG"', 'event_class': 'OCCURRENCE'}]),
Span('on', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 14, 'event_ID': 'e27', 'expression': '"on"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('on', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 6, 'event_ID': 'e28', 'expression': '"on üksi"', 'event_annotation': 'EVENT STATE multiword="true"', 'event_class': 'STATE'}]),
Span('üksi', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 10, 'event_ID': 'e28', 'expression': '"on üksi"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('peaksid', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 16, 'event_ID': 'e29', 'expression': '"peaksid"', 'event_annotation': 'EVENT MODAL', 'event_class': 'MODAL'}]),
Span('abi', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 17, 'event_ID': 'e30', 'expression': '"abi"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('pakkuma', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 18, 'event_ID': 'e31', 'expression': '"pakkuma"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('leiavad', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 20, 'event_ID': 'e32', 'expression': '"leiavad"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('aidata', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 26, 'event_ID': 'e33', 'expression': '"aidata"', 'event_annotation': 'EVENT OCCURRENCE polarity="NEG"', 'event_class': 'OCCURRENCE'}]),
Span('pole', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 27, 'event_ID': 'e34', 'expression': '"pole võimalik"', 'event_annotation': 'EVENT STATE polarity="NEG" multiword="true"', 'event_class': 'STATE'}]),
Span('võimalik', [{'corpus_sentence_ID': 8, 'corpus_word_ID': 28, 'event_ID': 'e34', 'expression': '"pole võimalik"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('püüab', [{'corpus_sentence_ID': 9, 'corpus_word_ID': 1, 'event_ID': 'e35', 'expression': '"püüab"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('lahendusi', [{'corpus_sentence_ID': 9, 'corpus_word_ID': 2, 'event_ID': 'e36', 'expression': '"lahendusi"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('otsida', [{'corpus_sentence_ID': 9, 'corpus_word_ID': 3, 'event_ID': 'e37', 'expression': '"otsida"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('kiiranalüüsi', [{'corpus_sentence_ID': 9, 'corpus_word_ID': 5, 'event_ID': 'e38', 'expression': '"kiiranalüüsi tehes"', 'event_annotation': 'EVENT OCCURRENCE multiword="true"', 'event_class': 'OCCURRENCE'}]),
Span('tehes', [{'corpus_sentence_ID': 9, 'corpus_word_ID': 6, 'event_ID': 'e38', 'expression': '"kiiranalüüsi tehes"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'OCCURRENCE'}]),
Span('Tekib', [{'corpus_sentence_ID': 10, 'corpus_word_ID': 0, 'event_ID': 'e39', 'expression': '"Tekib"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('ülevaadet', [{'corpus_sentence_ID': 10, 'corpus_word_ID': 4, 'event_ID': 'e41', 'expression': '"ülevaadet polnudki"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('toimuvast', [{'corpus_sentence_ID': 10, 'corpus_word_ID': 6, 'event_ID': 'e40', 'expression': '"toimuvast"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('polnudki', [{'corpus_sentence_ID': 10, 'corpus_word_ID': 10, 'event_ID': 'e41', 'expression': '"ülevaadet polnudki"', 'event_annotation': 'EVENT STATE polarity="NEG" multiword="true"', 'event_class': 'STATE'}]),
Span('probleemidest', [{'corpus_sentence_ID': 11, 'corpus_word_ID': 2, 'event_ID': 'e42', 'expression': '"probleemidest"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('õpitud', [{'corpus_sentence_ID': 11, 'corpus_word_ID': 4, 'event_ID': 'e43', 'expression': '"õpitud"', 'event_annotation': 'EVENT OCCURRENCE polarity="NEG"', 'event_class': 'OCCURRENCE'}]),
Span('hinnang', [{'corpus_sentence_ID': 12, 'corpus_word_ID': 3, 'event_ID': 'e44', 'expression': '"hinnang"', 'event_annotation': 'EVENT OCCURRENCE comment="vaieldav, kas märgendada"', 'event_class': 'OCCURRENCE'}]),
Span('tuleb', [{'corpus_sentence_ID': 12, 'corpus_word_ID': 4, 'event_ID': 'e45', 'expression': '"tuleb"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('püütakse', [{'corpus_sentence_ID': 12, 'corpus_word_ID': 8, 'event_ID': 'e46', 'expression': '"püütakse"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('euroläbirääkimiste', [{'corpus_sentence_ID': 12, 'corpus_word_ID': 10, 'event_ID': 'e47', 'expression': '"euroläbirääkimiste"', 'event_annotation': 'EVENT OCCURRENCE comment="vaieldav, kas märgendada"', 'event_class': 'OCCURRENCE'}]),
Span('ilustada', [{'corpus_sentence_ID': 12, 'corpus_word_ID': 12, 'event_ID': 'e48', 'expression': '"ilustada"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('sundis', [{'corpus_sentence_ID': 13, 'corpus_word_ID': 11, 'event_ID': 'e49', 'expression': '"sundis"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('kergitama', [{'corpus_sentence_ID': 13, 'corpus_word_ID': 14, 'event_ID': 'e50', 'expression': '"kergitama"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('nutavad', [{'corpus_sentence_ID': 13, 'corpus_word_ID': 17, 'event_ID': 'e51', 'expression': '"nutavad"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('muretseb', [{'corpus_sentence_ID': 15, 'corpus_word_ID': 1, 'event_ID': 'e52', 'expression': '"muretseb"', 'event_annotation': 'EVENT I_STATE', 'event_class': 'I_STATE'}]),
Span('laenu', [{'corpus_sentence_ID': 15, 'corpus_word_ID': 6, 'event_ID': 'e53', 'expression': '"laenu"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('saada', [{'corpus_sentence_ID': 15, 'corpus_word_ID': 8, 'event_ID': 'e54', 'expression': '"saada"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('leiab', [{'corpus_sentence_ID': 16, 'corpus_word_ID': 1, 'event_ID': 'e55', 'expression': '"leiab"', 'event_annotation': 'EVENT I_STATE', 'event_class': 'I_STATE'}]),
Span('abi', [{'corpus_sentence_ID': 16, 'corpus_word_ID': 5, 'event_ID': 'e56', 'expression': '"abi"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('on', [{'corpus_sentence_ID': 16, 'corpus_word_ID': 8, 'event_ID': 'e57', 'expression': '"on raiskamine"', 'event_annotation': 'EVENT STATE multiword="true"', 'event_class': 'STATE'}]),
Span('raiskamine', [{'corpus_sentence_ID': 16, 'corpus_word_ID': 9, 'event_ID': 'e57', 'expression': '"on raiskamine"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('oodatakse', [{'corpus_sentence_ID': 17, 'corpus_word_ID': 2, 'event_ID': 'e58', 'expression': '"oodatakse"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('oodatakse', [{'corpus_sentence_ID': 17, 'corpus_word_ID': 4, 'event_ID': 'e59', 'expression': '"oodatakse"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('töötatakse', [{'corpus_sentence_ID': 18, 'corpus_word_ID': 2, 'event_ID': 'e60', 'expression': '"töötatakse"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('katmiseks', [{'corpus_sentence_ID': 18, 'corpus_word_ID': 7, 'event_ID': 'e61', 'expression': '"katmiseks"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('saa', [{'corpus_sentence_ID': 18, 'corpus_word_ID': 10, 'event_ID': 'e62', 'expression': '"saa"', 'event_annotation': 'EVENT MODAL polarity="NEG"', 'event_class': 'MODAL'}]),
Span('vaadata', [{'corpus_sentence_ID': 18, 'corpus_word_ID': 12, 'event_ID': 'e63', 'expression': '"vaadata"', 'event_annotation': 'EVENT OCCURRENCE polarity="NEG" comment="fraas: vaadata üksikjuhtumina"', 'event_class': 'OCCURRENCE'}]),
Span('lonkab', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 2, 'event_ID': 'e64', 'expression': '"lonkab"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('jõuta', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 6, 'event_ID': 'e65', 'expression': '"jõuta"', 'event_annotation': 'EVENT I_STATE polarity="NEG" comment="ka OCCURRENCE"', 'event_class': 'I_STATE'}]),
Span('kokkuleppele', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 7, 'event_ID': 'e66', 'expression': '"kokkuleppele"', 'event_annotation': 'EVENT OCCURRENCE polarity="NEG"', 'event_class': 'OCCURRENCE'}]),
Span('on', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 11, 'event_ID': 'e67', 'expression': '"on haige"', 'event_annotation': 'EVENT STATE multiword="true"', 'event_class': 'STATE'}]),
Span('haige', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 12, 'event_ID': 'e67', 'expression': '"on haige"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('on', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 14, 'event_ID': 'e68', 'expression': '"on tegu"', 'event_annotation': 'EVENT STATE multiword="true"', 'event_class': 'STATE'}]),
Span('tegu', [{'corpus_sentence_ID': 19, 'corpus_word_ID': 15, 'event_ID': 'e68', 'expression': '"on tegu"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('kuuluvad', [{'corpus_sentence_ID': 20, 'corpus_word_ID': 5, 'event_ID': 'e69', 'expression': '"kuuluvad"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('on', [{'corpus_sentence_ID': 20, 'corpus_word_ID': 11, 'event_ID': 'e70', 'expression': '"on"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('olnud', [{'corpus_sentence_ID': 21, 'corpus_word_ID': 4, 'event_ID': 'e71', 'expression': '"olnud"', 'event_annotation': 'EVENT STATE comment="vaieldav, kas märgendada"', 'event_class': 'STATE'}]),
Span('ühistegevust', [{'corpus_sentence_ID': 21, 'corpus_word_ID': 5, 'event_ID': 'e72', 'expression': '"ühistegevust"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('toetada', [{'corpus_sentence_ID': 21, 'corpus_word_ID': 10, 'event_ID': 'e73', 'expression': '"toetada"', 'event_annotation': 'EVENT I_ACTION polarity="NEG"', 'event_class': 'I_ACTION'}]),
Span('tahtnud', [{'corpus_sentence_ID': 21, 'corpus_word_ID': 11, 'event_ID': 'e74', 'expression': '"tahtnud"', 'event_annotation': 'EVENT I_STATE polarity="NEG"', 'event_class': 'I_STATE'}]),
Span('õitseksid', [{'corpus_sentence_ID': 22, 'corpus_word_ID': 3, 'event_ID': 'e75', 'expression': '"õitseksid"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('pudeneks', [{'corpus_sentence_ID': 22, 'corpus_word_ID': 9, 'event_ID': 'e76', 'expression': '"pudeneks"', 'event_annotation': 'EVENT OCCURRENCE polarity="NEG"', 'event_class': 'OCCURRENCE'}]),
Span('pidamine', [{'corpus_sentence_ID': 23, 'corpus_word_ID': 4, 'event_ID': 'e77', 'expression': '"pidamine"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('tundub', [{'corpus_sentence_ID': 23, 'corpus_word_ID': 5, 'event_ID': 'e78', 'expression': '"tundub tühine"', 'event_annotation': 'EVENT I_STATE multiword="true"', 'event_class': 'I_STATE'}]),
Span('tühine', [{'corpus_sentence_ID': 23, 'corpus_word_ID': 10, 'event_ID': 'e78', 'expression': '"tundub tühine"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'I_STATE'}]),
Span('pole', [{'corpus_sentence_ID': 24, 'corpus_word_ID': 2, 'event_ID': 'e79', 'expression': '"pole"', 'event_annotation': 'EVENT STATE polarity="NEG"', 'event_class': 'STATE'}]),
Span('võtta', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 5, 'event_ID': 'e80', 'expression': '"võtta"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('on', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 9, 'event_ID': 'e81', 'expression': '"on otstarbekam"', 'event_annotation': 'EVENT STATE multiword="true"', 'event_class': 'STATE'}]),
Span('otstarbekam', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 10, 'event_ID': 'e81', 'expression': '"on otstarbekam"', 'event_annotation': 'EVENT multiword="true"', 'event_class': 'STATE'}]),
Span('maksta', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 13, 'event_ID': 'e82', 'expression': '"maksta"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('anda', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 20, 'event_ID': 'e83', 'expression': '"anda"', 'event_annotation': 'EVENT I_ACTION', 'event_class': 'I_ACTION'}]),
Span('võimalus', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 22, 'event_ID': 'e84', 'expression': '"võimalus"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('tulla', [{'corpus_sentence_ID': 25, 'corpus_word_ID': 25, 'event_ID': 'e85', 'expression': '"tulla"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('oskavad', [{'corpus_sentence_ID': 26, 'corpus_word_ID': 5, 'event_ID': 'e86', 'expression': '"oskavad"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('austavad', [{'corpus_sentence_ID': 26, 'corpus_word_ID': 7, 'event_ID': 'e87', 'expression': '"austavad"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('võetakse', [{'corpus_sentence_ID': 27, 'corpus_word_ID': 3, 'event_ID': 'e88', 'expression': '"võetakse"', 'event_annotation': 'EVENT OCCURRENCE comment="fraas: võetakse loomuliku nähtusena"', 'event_class': 'OCCURRENCE'}]),
Span('jäägi', [{'corpus_sentence_ID': 28, 'corpus_word_ID': 2, 'event_ID': 'e89', 'expression': '"jäägi"', 'event_annotation': 'EVENT STATE polarity="NEG" comment="ka OCCURRENCE"', 'event_class': 'STATE'}]),
Span('võtta', [{'corpus_sentence_ID': 28, 'corpus_word_ID': 14, 'event_ID': 'e90', 'expression': '"võtta"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('viia', [{'corpus_sentence_ID': 28, 'corpus_word_ID': 19, 'event_ID': 'e91', 'expression': '"viia"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}]),
Span('saamata', [{'corpus_sentence_ID': 29, 'corpus_word_ID': 1, 'event_ID': 'e92', 'expression': '"saamata"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('järjekord', [{'corpus_sentence_ID': 29, 'corpus_word_ID': 4, 'event_ID': 'e93', 'expression': '"järjekord"', 'event_annotation': 'EVENT STATE', 'event_class': 'STATE'}]),
Span('maksan', [{'corpus_sentence_ID': 29, 'corpus_word_ID': 6, 'event_ID': 'e94', 'expression': '"maksan"', 'event_annotation': 'EVENT OCCURRENCE', 'event_class': 'OCCURRENCE'}])])

In [72]:
article_text.gold_timexes

Layer(name='gold_timexes', attributes=('corpus_sentence_ID', 'corpus_word_ID', 'timex_ID', 'expression', 'timex_annotation', 'type', 'value'), spans=SL[Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}]),
Span('aastaid', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 1, 'timex_ID': 't2', 'expression': '"aastaid"', 'timex_annotation': 'TIMEX DURATION PXY', 'type': 'DURATION', 'value': 'PXY'}]),
Span('kuude', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 7, 'timex_ID': 't3', 'expression': '"kuude kaupa"', 'timex_annotation': 'TIMEX DURATION PXM multiword="true"', 'type': 'DURATION', 'value': 'PXM'}]),
Span('kaupa', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 8, 'timex_ID': 't3', 'expression': '"kuude kaupa"', 'timex_annotation': 'TIMEX multiword="true"', 'type': 'DURATION', 'value': 'PXM'}]),
Span('seitse', [{'corpus_sentence_ID': 5, 'corpus_word_ID': 8, 'timex_ID': 't4', 'expression': '"seitse kuud"', 'timex_annotation': 'TIMEX DURATION P7M multiword="true"', 'type': 'DURATION', 'value': 'P7M'}]),
Span('kuud', [{'corpus_sentence_ID': 5, 'corpus_word_ID': 9, 'timex_ID': 't4', 'expression': '"seitse kuud"', 'timex_annotation': 'TIMEX multiword="true"', 'type': 'DURATION', 'value': 'P7M'}]),
Span('kuude', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 1, 'timex_ID': 't5', 'expression': '"kuude kaupa"', 'timex_annotation': 'TIMEX DURATION PXM multiword="true"', 'type': 'DURATION', 'value': 'PXM'}]),
Span('kaupa', [{'corpus_sentence_ID': 7, 'corpus_word_ID': 2, 'timex_ID': 't5', 'expression': '"kuude kaupa"', 'timex_annotation': 'TIMEX multiword="true"', 'type': 'DURATION', 'value': 'PXM'}]),
Span('varem', [{'corpus_sentence_ID': 10, 'corpus_word_ID': 9, 'timex_ID': 't6', 'expression': '"varem"', 'timex_annotation': 'TIMEX DATE PAST_REF', 'type': 'DATE', 'value': 'PAST_REF'}]),
Span('senistest', [{'corpus_sentence_ID': 11, 'corpus_word_ID': 1, 'timex_ID': 't7', 'expression': '"senistest"', 'timex_annotation': 'TIMEX DATE PRESENT_REF', 'type': 'DATE', 'value': 'PRESENT_REF'}]),
Span('kunagi', [{'corpus_sentence_ID': 13, 'corpus_word_ID': 10, 'timex_ID': 't8', 'expression': '"kunagi"', 'timex_annotation': 'TIMEX DATE PAST_REF', 'type': 'DATE', 'value': 'PAST_REF'}]),
Span('praegu', [{'corpus_sentence_ID': 18, 'corpus_word_ID': 1, 'timex_ID': 't9', 'expression': '"praegu"', 'timex_annotation': 'TIMEX DATE PRESENT_REF', 'type': 'DATE', 'value': 'PRESENT_REF'}]),
Span('kunagi', [{'corpus_sentence_ID': 21, 'corpus_word_ID': 1, 'timex_ID': 't10', 'expression': '"kunagi"', 'timex_annotation': 'TIMEX DATE PAST_REF', 'type': 'DATE', 'value': 'PAST_REF'}]),
Span('tänases', [{'corpus_sentence_ID': 27, 'corpus_word_ID': 4, 'timex_ID': 't11', 'expression': '"tänases"', 'timex_annotation': 'TIMEX DATE PRESENT_REF', 'type': 'DATE', 'value': 'PRESENT_REF'}]),
Span('ühel', [{'corpus_sentence_ID': 28, 'corpus_word_ID': 4, 'timex_ID': 't12', 'expression': '"ühel heal päeval"', 'timex_annotation': 'TIMEX DATE XXXX-XX-XX multiword="true"', 'type': 'DATE', 'value': 'XXXX-XX-XX'}]),
Span('heal', [{'corpus_sentence_ID': 28, 'corpus_word_ID': 5, 'timex_ID': 't12', 'expression': '"ühel heal päeval"', 'timex_annotation': 'TIMEX multiword="true"', 'type': 'DATE', 'value': 'XXXX-XX-XX'}]),
Span('päeval', [{'corpus_sentence_ID': 28, 'corpus_word_ID': 6, 'timex_ID': 't12', 'expression': '"ühel heal päeval"', 'timex_annotation': 'TIMEX multiword="true"', 'type': 'DATE', 'value': 'XXXX-XX-XX'}])])

Layers for events with IOB-annotations, event phrases and timex phrases can be added separately:

In [73]:
gold_word_events = create_gold_word_events_layer(article_text, baseAnnotations.get('aja_ml_2002_47.tasak.a023.sol'))

In [74]:
gold_event_phrases = create_gold_event_phrases(article_text)

In [75]:
gold_timex_phrases = create_gold_timex_phrases(article_text)

In [76]:
article_text = add_layers_to_text('aja_ml_2002_47.tasak.a023.sol', article_text, articlesDCT, 
                                  [gold_word_events, gold_event_phrases, gold_timex_phrases])

In [77]:
article_text.gold_word_events

Layer(name='gold_word_events', attributes=('nertag',), spans=SL[EnvelopingSpan(['20.11.2002'], [{'nertag': 'O'}]),
EnvelopingSpan(['Juba'], [{'nertag': 'O'}]),
EnvelopingSpan(['aastaid'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'O'}]),
EnvelopingSpan(['piimavarumisel'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['kestnud'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['anarhia'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Kui'], [{'nertag': 'O'}]),
EnvelopingSpan(['vahepeal'], [{'nertag': 'O'}]),
EnvelopingSpan(['tundubki'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['et'], [{'nertag': 'O'}]),
EnvelopingSpan(['suuremad'], [{'nertag': 'O'}]),
EnvelopingSpan(['hädad'], [{'nertag': 'O'}]),
EnvelopingSpan(['hakkavad'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['mööda'], [{'nertag': 'O'}]),
EnvelopingSpan(['saama'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['tuleb'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['uus'], [{'nertag': 'O'}]),
EnvelopingSpan(['löök'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['See'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['et'], [{'nertag': 'O'}]),
EnvelopingSpan(['Rapla'], [{'nertag': 'O'}]),
EnvelopingSpan(['Dairy'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['lehmapidajatele'], [{'nertag': 'O'}]),
EnvelopingSpan(['kuude'], [{'nertag': 'O'}]),
EnvelopingSpan(['kaupa'], [{'nertag': 'O'}]),
EnvelopingSpan(['võlgu'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['pälvis'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['laiemat'], [{'nertag': 'O'}]),
EnvelopingSpan(['tähelepanu'], [{'nertag': 'O'}]),
EnvelopingSpan(['alles'], [{'nertag': 'O'}]),
EnvelopingSpan(['siis'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kui'], [{'nertag': 'O'}]),
EnvelopingSpan(['riik'], [{'nertag': 'O'}]),
EnvelopingSpan(['tahtis'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['firmat'], [{'nertag': 'O'}]),
EnvelopingSpan(['juhtivale'], [{'nertag': 'O'}]),
EnvelopingSpan(['Afganistani'], [{'nertag': 'O'}]),
EnvelopingSpan(['eruohvitserile'], [{'nertag': 'O'}]),
EnvelopingSpan(['Jaqub'], [{'nertag': 'O'}]),
EnvelopingSpan(['Haidaryle'], [{'nertag': 'O'}]),
EnvelopingSpan(['eriliste'], [{'nertag': 'O'}]),
EnvelopingSpan(['teenete'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['eest'], [{'nertag': 'O'}]),
EnvelopingSpan(['kodakondsuse'], [{'nertag': 'O'}]),
EnvelopingSpan(['kinkida'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Mure'], [{'nertag': 'O'}]),
EnvelopingSpan(['suuruse'], [{'nertag': 'O'}]),
EnvelopingSpan(['võtab'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['oma'], [{'nertag': 'O'}]),
EnvelopingSpan(['ilmekas'], [{'nertag': 'O'}]),
EnvelopingSpan(['lihtsuses'], [{'nertag': 'O'}]),
EnvelopingSpan(['kokku'], [{'nertag': 'O'}]),
EnvelopingSpan(['põllumajandusministeeriumile'], [{'nertag': 'O'}]),
EnvelopingSpan(['saadetud'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['abipalve'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Selle'], [{'nertag': 'O'}]),
EnvelopingSpan(['kirjutasid'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['kaheksa'], [{'nertag': 'O'}]),
EnvelopingSpan(['Noarootsi'], [{'nertag': 'O'}]),
EnvelopingSpan(['lehmapidajat'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kel'], [{'nertag': 'O'}]),
EnvelopingSpan(['piimaraha'], [{'nertag': 'O'}]),
EnvelopingSpan(['seitse'], [{'nertag': 'O'}]),
EnvelopingSpan(['kuud'], [{'nertag': 'O'}]),
EnvelopingSpan(['saamata'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Kirjas'], [{'nertag': 'O'}]),
EnvelopingSpan(['seisab'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([':'], [{'nertag': 'O'}]),
EnvelopingSpan(['"'], [{'nertag': 'O'}]),
EnvelopingSpan(['Võimaluse'], [{'nertag': 'O'}]),
EnvelopingSpan(['piires'], [{'nertag': 'O'}]),
EnvelopingSpan(['palume'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tasuta'], [{'nertag': 'O'}]),
EnvelopingSpan(['abi'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['juristi'], [{'nertag': 'O'}]),
EnvelopingSpan(['või'], [{'nertag': 'O'}]),
EnvelopingSpan(['advokaadi'], [{'nertag': 'O'}]),
EnvelopingSpan(['näol'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kes'], [{'nertag': 'O'}]),
EnvelopingSpan(['tunneks'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['seadusi'], [{'nertag': 'O'}]),
EnvelopingSpan(['ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['oskaks'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['meid'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['vaeseid'], [{'nertag': 'O'}]),
EnvelopingSpan(['piimatootjaid'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kaitsta'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['"'], [{'nertag': 'O'}]),
EnvelopingSpan(['Mida'], [{'nertag': 'O'}]),
EnvelopingSpan(['kuude'], [{'nertag': 'O'}]),
EnvelopingSpan(['kaupa'], [{'nertag': 'O'}]),
EnvelopingSpan(['saamata'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['piimaraha'], [{'nertag': 'O'}]),
EnvelopingSpan(['tähendab'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['pole'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['vaja'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['seletada'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['maainimesele'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kellele'], [{'nertag': 'O'}]),
EnvelopingSpan(['see'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['üks'], [{'nertag': 'O'}]),
EnvelopingSpan(['põhilisi'], [{'nertag': 'O'}]),
EnvelopingSpan(['elatusallikaid'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Mis'], [{'nertag': 'O'}]),
EnvelopingSpan(['kõige'], [{'nertag': 'O'}]),
EnvelopingSpan(['hullem'], [{'nertag': 'O'}]),
EnvelopingSpan(['-'], [{'nertag': 'O'}]),
EnvelopingSpan(['need'], [{'nertag': 'O'}]),
EnvelopingSpan(['inimesed'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['oma'], [{'nertag': 'O'}]),
EnvelopingSpan(['murega'], [{'nertag': 'O'}]),
EnvelopingSpan(['sisuliselt'], [{'nertag': 'O'}]),
EnvelopingSpan(['üksi'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['sest'], [{'nertag': 'O'}]),
EnvelopingSpan(['need'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kes'], [{'nertag': 'O'}]),
EnvelopingSpan(['peaksid'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['abi'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['pakkuma'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['leiavad'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['alati'], [{'nertag': 'O'}]),
EnvelopingSpan(['tuhat'], [{'nertag': 'O'}]),
EnvelopingSpan(['põhjendust'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['miks'], [{'nertag': 'O'}]),
EnvelopingSpan(['aidata'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['pole'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['võimalik'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Põllumajandusministeerium'], [{'nertag': 'O'}]),
EnvelopingSpan(['püüab'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['lahendusi'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['otsida'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['piimasektorile'], [{'nertag': 'O'}]),
EnvelopingSpan(['kiiranalüüsi'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tehes'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Tekib'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['küsimus'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kas'], [{'nertag': 'O'}]),
EnvelopingSpan(['ülevaadet'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['piimanduses'], [{'nertag': 'O'}]),
EnvelopingSpan(['toimuvast'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['siis'], [{'nertag': 'O'}]),
EnvelopingSpan(['ministeeriumil'], [{'nertag': 'O'}]),
EnvelopingSpan(['varem'], [{'nertag': 'O'}]),
EnvelopingSpan(['polnudki'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Kas'], [{'nertag': 'O'}]),
EnvelopingSpan(['senistest'], [{'nertag': 'O'}]),
EnvelopingSpan(['probleemidest'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['pole'], [{'nertag': 'O'}]),
EnvelopingSpan(['õpitud'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['?'], [{'nertag': 'O'}]),
EnvelopingSpan(['Ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['kas'], [{'nertag': 'O'}]),
EnvelopingSpan(['see'], [{'nertag': 'O'}]),
EnvelopingSpan(['hinnang'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tuleb'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ikka'], [{'nertag': 'O'}]),
EnvelopingSpan(['objektiivne'], [{'nertag': 'O'}]),
EnvelopingSpan(['või'], [{'nertag': 'O'}]),
EnvelopingSpan(['püütakse'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['seisu'], [{'nertag': 'O'}]),
EnvelopingSpan(['euroläbirääkimiste'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['taustal'], [{'nertag': 'O'}]),
EnvelopingSpan(['ilustada'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Teised'], [{'nertag': 'O'}]),
EnvelopingSpan(['piimatööstused'], [{'nertag': 'O'}]),
EnvelopingSpan(['vaevalt'], [{'nertag': 'O'}]),
EnvelopingSpan(['Dairyt'], [{'nertag': 'O'}]),
EnvelopingSpan(['ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['tema'], [{'nertag': 'O'}]),
EnvelopingSpan(['eelkäijat'], [{'nertag': 'O'}]),
EnvelopingSpan(['Lactot'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kes'], [{'nertag': 'O'}]),
EnvelopingSpan(['kunagi'], [{'nertag': 'O'}]),
EnvelopingSpan(['sundis'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['neid'], [{'nertag': 'O'}]),
EnvelopingSpan(['kokkuostuhinda'], [{'nertag': 'O'}]),
EnvelopingSpan(['kergitama'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['taga'], [{'nertag': 'O'}]),
EnvelopingSpan(['nutavad'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Üks'], [{'nertag': 'O'}]),
EnvelopingSpan(['konkurent'], [{'nertag': 'O'}]),
EnvelopingSpan(['vähem'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Pank'], [{'nertag': 'O'}]),
EnvelopingSpan(['muretseb'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['jälle'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kuidas'], [{'nertag': 'O'}]),
EnvelopingSpan(['oma'], [{'nertag': 'O'}]),
EnvelopingSpan(['laenu'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tagasi'], [{'nertag': 'O'}]),
EnvelopingSpan(['saada'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Peaminister'], [{'nertag': 'O'}]),
EnvelopingSpan(['leiab'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['et'], [{'nertag': 'O'}]),
EnvelopingSpan(['rahaline'], [{'nertag': 'O'}]),
EnvelopingSpan(['abi'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['raskustes'], [{'nertag': 'O'}]),
EnvelopingSpan(['firmadele'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['raiskamine'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Aga'], [{'nertag': 'O'}]),
EnvelopingSpan(['maal'], [{'nertag': 'O'}]),
EnvelopingSpan(['oodatakse'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['oodatakse'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['piimaraha'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Kuigi'], [{'nertag': 'O'}]),
EnvelopingSpan(['praegu'], [{'nertag': 'O'}]),
EnvelopingSpan(['töötatakse'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['välja'], [{'nertag': 'O'}]),
EnvelopingSpan(['skeemi'], [{'nertag': 'O'}]),
EnvelopingSpan(['Dairy'], [{'nertag': 'O'}]),
EnvelopingSpan(['võlgade'], [{'nertag': 'O'}]),
EnvelopingSpan(['katmiseks'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['ei'], [{'nertag': 'O'}]),
EnvelopingSpan(['saa'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['Dairyt'], [{'nertag': 'O'}]),
EnvelopingSpan(['vaadata'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ainult'], [{'nertag': 'O'}]),
EnvelopingSpan(['üksikjuhtumina'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Kogu'], [{'nertag': 'O'}]),
EnvelopingSpan(['süsteem'], [{'nertag': 'O'}]),
EnvelopingSpan(['lonkab'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['ainult'], [{'nertag': 'O'}]),
EnvelopingSpan(['ei'], [{'nertag': 'O'}]),
EnvelopingSpan(['jõuta'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['kokkuleppele'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kumb'], [{'nertag': 'O'}]),
EnvelopingSpan(['jalg'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['haige'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['või'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tegu'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['hoopis'], [{'nertag': 'O'}]),
EnvelopingSpan(['psüühikahäirega'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Teistes'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['arenenumates'], [{'nertag': 'O'}]),
EnvelopingSpan(['riikides'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kuuluvad'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['piimatööstused'], [{'nertag': 'O'}]),
EnvelopingSpan(['enamasti'], [{'nertag': 'O'}]),
EnvelopingSpan(['ühistutele'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['mis'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tootjate'], [{'nertag': 'O'}]),
EnvelopingSpan(['endi'], [{'nertag': 'O'}]),
EnvelopingSpan(['omad'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Meil'], [{'nertag': 'O'}]),
EnvelopingSpan(['kunagi'], [{'nertag': 'O'}]),
EnvelopingSpan(['õitsval'], [{'nertag': 'O'}]),
EnvelopingSpan(['järjel'], [{'nertag': 'O'}]),
EnvelopingSpan(['olnud'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ühistegevust'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['pole'], [{'nertag': 'O'}]),
EnvelopingSpan(['aga'], [{'nertag': 'O'}]),
EnvelopingSpan(['riik'], [{'nertag': 'O'}]),
EnvelopingSpan(['piisavalt'], [{'nertag': 'O'}]),
EnvelopingSpan(['toetada'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tahtnud'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Et'], [{'nertag': 'O'}]),
EnvelopingSpan(['suuremad'], [{'nertag': 'O'}]),
EnvelopingSpan(['ärid'], [{'nertag': 'O'}]),
EnvelopingSpan(['õitseksid'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['raha'], [{'nertag': 'O'}]),
EnvelopingSpan(['liiga'], [{'nertag': 'O'}]),
EnvelopingSpan(['laiali'], [{'nertag': 'O'}]),
EnvelopingSpan(['ei'], [{'nertag': 'O'}]),
EnvelopingSpan(['pudeneks'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Ühe'], [{'nertag': 'O'}]),
EnvelopingSpan(['või'], [{'nertag': 'O'}]),
EnvelopingSpan(['paari'], [{'nertag': 'O'}]),
EnvelopingSpan(['lehma'], [{'nertag': 'O'}]),
EnvelopingSpan(['pidamine'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tundub'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['selle'], [{'nertag': 'O'}]),
EnvelopingSpan(['kõrval'], [{'nertag': 'O'}]),
EnvelopingSpan(['ju'], [{'nertag': 'O'}]),
EnvelopingSpan(['nii'], [{'nertag': 'O'}]),
EnvelopingSpan(['tühine'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Ent'], [{'nertag': 'O'}]),
EnvelopingSpan(['asi'], [{'nertag': 'O'}]),
EnvelopingSpan(['pole'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['mitte'], [{'nertag': 'O'}]),
EnvelopingSpan(['lehmades'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['vaid'], [{'nertag': 'O'}]),
EnvelopingSpan(['inimestes'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Kui'], [{'nertag': 'O'}]),
EnvelopingSpan(['asja'], [{'nertag': 'O'}]),
EnvelopingSpan(['kas'], [{'nertag': 'O'}]),
EnvelopingSpan(['või'], [{'nertag': 'O'}]),
EnvelopingSpan(['puhtmajanduslikult'], [{'nertag': 'O'}]),
EnvelopingSpan(['võtta'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['siis'], [{'nertag': 'O'}]),
EnvelopingSpan(['kumb'], [{'nertag': 'O'}]),
EnvelopingSpan(['on'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['otstarbekam'], [{'nertag': 'I-EVENT'}]),
EnvelopingSpan([':'], [{'nertag': 'O'}]),
EnvelopingSpan(['kas'], [{'nertag': 'O'}]),
EnvelopingSpan(['maksta'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['vaesematele'], [{'nertag': 'O'}]),
EnvelopingSpan(['maainimestele'], [{'nertag': 'O'}]),
EnvelopingSpan(['näljapajukit'], [{'nertag': 'O'}]),
EnvelopingSpan(['sotsiaaltoetuste'], [{'nertag': 'O'}]),
EnvelopingSpan(['näol'], [{'nertag': 'O'}]),
EnvelopingSpan(['või'], [{'nertag': 'O'}]),
EnvelopingSpan(['anda'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['neile'], [{'nertag': 'O'}]),
EnvelopingSpan(['võimalus'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ise'], [{'nertag': 'O'}]),
EnvelopingSpan(['toime'], [{'nertag': 'O'}]),
EnvelopingSpan(['tulla'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Läbi'], [{'nertag': 'O'}]),
EnvelopingSpan(['töö'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['mida'], [{'nertag': 'O'}]),
EnvelopingSpan(['nad'], [{'nertag': 'O'}]),
EnvelopingSpan(['oskavad'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['austavad'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Ka'], [{'nertag': 'O'}]),
EnvelopingSpan(['ilmset'], [{'nertag': 'O'}]),
EnvelopingSpan(['ebaõiglust'], [{'nertag': 'O'}]),
EnvelopingSpan(['võetakse'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['tänases'], [{'nertag': 'O'}]),
EnvelopingSpan(['Eestis'], [{'nertag': 'O'}]),
EnvelopingSpan(['järjest'], [{'nertag': 'O'}]),
EnvelopingSpan(['enam'], [{'nertag': 'O'}]),
EnvelopingSpan(['loomuliku'], [{'nertag': 'O'}]),
EnvelopingSpan(['nähtusena'], [{'nertag': 'O'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Nii'], [{'nertag': 'O'}]),
EnvelopingSpan(['ei'], [{'nertag': 'O'}]),
EnvelopingSpan(['jäägi'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['talumehel'], [{'nertag': 'O'}]),
EnvelopingSpan(['ühel'], [{'nertag': 'O'}]),
EnvelopingSpan(['heal'], [{'nertag': 'O'}]),
EnvelopingSpan(['päeval'], [{'nertag': 'O'}]),
EnvelopingSpan(['muud'], [{'nertag': 'O'}]),
EnvelopingSpan(['üle'], [{'nertag': 'O'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['kui'], [{'nertag': 'O'}]),
EnvelopingSpan(['viimane'], [{'nertag': 'O'}]),
EnvelopingSpan(['lehm'], [{'nertag': 'O'}]),
EnvelopingSpan(['käekõrvale'], [{'nertag': 'O'}]),
EnvelopingSpan(['võtta'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['ja'], [{'nertag': 'O'}]),
EnvelopingSpan(['advokaadi'], [{'nertag': 'O'}]),
EnvelopingSpan(['ukse'], [{'nertag': 'O'}]),
EnvelopingSpan(['taha'], [{'nertag': 'O'}]),
EnvelopingSpan(['viia'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan(['.'], [{'nertag': 'O'}]),
EnvelopingSpan(['Piimaraha'], [{'nertag': 'O'}]),
EnvelopingSpan(['saamata'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),
EnvelopingSpan(['tapamajas'], [{'nertag': 'O'}]),
EnvelopingSpan(['järjekord'], [{'nertag': 'B-EVENT'}]),
EnvelopingSpan([','], [{'nertag': 'O'}]),

In [78]:
article_text.gold_event_phrases

Layer(name='gold_event_phrases', attributes=('event_ID', 'expression', 'event_class'), spans=SL[EnvelopingSpan(['piimavarumisel'], [{'event_ID': 'e1', 'expression': '"piimavarumisel"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['kestnud'], [{'event_ID': 'e2', 'expression': '"kestnud"', 'event_class': 'ASPECTUAL'}]),
EnvelopingSpan(['anarhia'], [{'event_ID': 'e3', 'expression': '"anarhia"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['tundubki'], [{'event_ID': 'e4', 'expression': '"tundubki"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['hakkavad'], [{'event_ID': 'e5', 'expression': '"hakkavad"', 'event_class': 'ASPECTUAL'}]),
EnvelopingSpan(['saama'], [{'event_ID': 'e6', 'expression': '"saama"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['tuleb'], [{'event_ID': 'e7', 'expression': '"tuleb"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['on', 'võlgu'], [{'event_ID': 'e8', 'expression': '"on võlgu"', 'event_class': 'STATE'}]),
EnvelopingSpan(['pälvis'], [{'event_ID': 'e9', 'expression': '"pälvis"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['tahtis'], [{'event_ID': 'e10', 'expression': '"tahtis"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['teenete'], [{'event_ID': 'e11', 'expression': '"teenete"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['kinkida'], [{'event_ID': 'e12', 'expression': '"kinkida"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['võtab'], [{'event_ID': 'e13', 'expression': '"võtab"', 'event_class': 'STATE'}]),
EnvelopingSpan(['saadetud'], [{'event_ID': 'e14', 'expression': '"saadetud"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['kirjutasid'], [{'event_ID': 'e15', 'expression': '"kirjutasid"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['saamata'], [{'event_ID': 'e16', 'expression': '"saamata"', 'event_class': 'STATE'}]),
EnvelopingSpan(['seisab'], [{'event_ID': 'e17', 'expression': '"seisab"', 'event_class': 'STATE'}]),
EnvelopingSpan(['palume'], [{'event_ID': 'e18', 'expression': '"palume"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['abi'], [{'event_ID': 'e19', 'expression': '"abi"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['tunneks'], [{'event_ID': 'e20', 'expression': '"tunneks"', 'event_class': 'STATE'}]),
EnvelopingSpan(['oskaks'], [{'event_ID': 'e21', 'expression': '"oskaks"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['kaitsta'], [{'event_ID': 'e22', 'expression': '"kaitsta"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['saamata'], [{'event_ID': 'e23', 'expression': '"saamata"', 'event_class': 'STATE'}]),
EnvelopingSpan(['tähendab'], [{'event_ID': 'e24', 'expression': '"tähendab"', 'event_class': 'STATE'}]),
EnvelopingSpan(['pole', 'vaja'], [{'event_ID': 'e25', 'expression': '"pole vaja"', 'event_class': 'STATE'}]),
EnvelopingSpan(['seletada'], [{'event_ID': 'e26', 'expression': '"seletada"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['on'], [{'event_ID': 'e27', 'expression': '"on"', 'event_class': 'STATE'}]),
EnvelopingSpan(['on', 'üksi'], [{'event_ID': 'e28', 'expression': '"on üksi"', 'event_class': 'STATE'}]),
EnvelopingSpan(['peaksid'], [{'event_ID': 'e29', 'expression': '"peaksid"', 'event_class': 'MODAL'}]),
EnvelopingSpan(['abi'], [{'event_ID': 'e30', 'expression': '"abi"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['pakkuma'], [{'event_ID': 'e31', 'expression': '"pakkuma"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['leiavad'], [{'event_ID': 'e32', 'expression': '"leiavad"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['aidata'], [{'event_ID': 'e33', 'expression': '"aidata"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['pole', 'võimalik'], [{'event_ID': 'e34', 'expression': '"pole võimalik"', 'event_class': 'STATE'}]),
EnvelopingSpan(['püüab'], [{'event_ID': 'e35', 'expression': '"püüab"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['lahendusi'], [{'event_ID': 'e36', 'expression': '"lahendusi"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['otsida'], [{'event_ID': 'e37', 'expression': '"otsida"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['kiiranalüüsi', 'tehes'], [{'event_ID': 'e38', 'expression': '"kiiranalüüsi tehes"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['Tekib'], [{'event_ID': 'e39', 'expression': '"Tekib"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['ülevaadet', 'polnudki'], [{'event_ID': 'e41', 'expression': '"ülevaadet polnudki"', 'event_class': 'STATE'}]),
EnvelopingSpan(['toimuvast'], [{'event_ID': 'e40', 'expression': '"toimuvast"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['probleemidest'], [{'event_ID': 'e42', 'expression': '"probleemidest"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['õpitud'], [{'event_ID': 'e43', 'expression': '"õpitud"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['hinnang'], [{'event_ID': 'e44', 'expression': '"hinnang"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['tuleb'], [{'event_ID': 'e45', 'expression': '"tuleb"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['püütakse'], [{'event_ID': 'e46', 'expression': '"püütakse"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['euroläbirääkimiste'], [{'event_ID': 'e47', 'expression': '"euroläbirääkimiste"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['ilustada'], [{'event_ID': 'e48', 'expression': '"ilustada"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['sundis'], [{'event_ID': 'e49', 'expression': '"sundis"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['kergitama'], [{'event_ID': 'e50', 'expression': '"kergitama"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['nutavad'], [{'event_ID': 'e51', 'expression': '"nutavad"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['muretseb'], [{'event_ID': 'e52', 'expression': '"muretseb"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['laenu'], [{'event_ID': 'e53', 'expression': '"laenu"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['saada'], [{'event_ID': 'e54', 'expression': '"saada"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['leiab'], [{'event_ID': 'e55', 'expression': '"leiab"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['abi'], [{'event_ID': 'e56', 'expression': '"abi"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['on', 'raiskamine'], [{'event_ID': 'e57', 'expression': '"on raiskamine"', 'event_class': 'STATE'}]),
EnvelopingSpan(['oodatakse'], [{'event_ID': 'e58', 'expression': '"oodatakse"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['oodatakse'], [{'event_ID': 'e59', 'expression': '"oodatakse"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['töötatakse'], [{'event_ID': 'e60', 'expression': '"töötatakse"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['katmiseks'], [{'event_ID': 'e61', 'expression': '"katmiseks"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['saa'], [{'event_ID': 'e62', 'expression': '"saa"', 'event_class': 'MODAL'}]),
EnvelopingSpan(['vaadata'], [{'event_ID': 'e63', 'expression': '"vaadata"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['lonkab'], [{'event_ID': 'e64', 'expression': '"lonkab"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['jõuta'], [{'event_ID': 'e65', 'expression': '"jõuta"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['kokkuleppele'], [{'event_ID': 'e66', 'expression': '"kokkuleppele"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['on', 'haige'], [{'event_ID': 'e67', 'expression': '"on haige"', 'event_class': 'STATE'}]),
EnvelopingSpan(['on', 'tegu'], [{'event_ID': 'e68', 'expression': '"on tegu"', 'event_class': 'STATE'}]),
EnvelopingSpan(['kuuluvad'], [{'event_ID': 'e69', 'expression': '"kuuluvad"', 'event_class': 'STATE'}]),
EnvelopingSpan(['on'], [{'event_ID': 'e70', 'expression': '"on"', 'event_class': 'STATE'}]),
EnvelopingSpan(['olnud'], [{'event_ID': 'e71', 'expression': '"olnud"', 'event_class': 'STATE'}]),
EnvelopingSpan(['ühistegevust'], [{'event_ID': 'e72', 'expression': '"ühistegevust"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['toetada'], [{'event_ID': 'e73', 'expression': '"toetada"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['tahtnud'], [{'event_ID': 'e74', 'expression': '"tahtnud"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['õitseksid'], [{'event_ID': 'e75', 'expression': '"õitseksid"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['pudeneks'], [{'event_ID': 'e76', 'expression': '"pudeneks"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['pidamine'], [{'event_ID': 'e77', 'expression': '"pidamine"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['tundub', 'tühine'], [{'event_ID': 'e78', 'expression': '"tundub tühine"', 'event_class': 'I_STATE'}]),
EnvelopingSpan(['pole'], [{'event_ID': 'e79', 'expression': '"pole"', 'event_class': 'STATE'}]),
EnvelopingSpan(['võtta'], [{'event_ID': 'e80', 'expression': '"võtta"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['on', 'otstarbekam'], [{'event_ID': 'e81', 'expression': '"on otstarbekam"', 'event_class': 'STATE'}]),
EnvelopingSpan(['maksta'], [{'event_ID': 'e82', 'expression': '"maksta"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['anda'], [{'event_ID': 'e83', 'expression': '"anda"', 'event_class': 'I_ACTION'}]),
EnvelopingSpan(['võimalus'], [{'event_ID': 'e84', 'expression': '"võimalus"', 'event_class': 'STATE'}]),
EnvelopingSpan(['tulla'], [{'event_ID': 'e85', 'expression': '"tulla"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['oskavad'], [{'event_ID': 'e86', 'expression': '"oskavad"', 'event_class': 'STATE'}]),
EnvelopingSpan(['austavad'], [{'event_ID': 'e87', 'expression': '"austavad"', 'event_class': 'STATE'}]),
EnvelopingSpan(['võetakse'], [{'event_ID': 'e88', 'expression': '"võetakse"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['jäägi'], [{'event_ID': 'e89', 'expression': '"jäägi"', 'event_class': 'STATE'}]),
EnvelopingSpan(['võtta'], [{'event_ID': 'e90', 'expression': '"võtta"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['viia'], [{'event_ID': 'e91', 'expression': '"viia"', 'event_class': 'OCCURRENCE'}]),
EnvelopingSpan(['saamata'], [{'event_ID': 'e92', 'expression': '"saamata"', 'event_class': 'STATE'}]),
EnvelopingSpan(['järjekord'], [{'event_ID': 'e93', 'expression': '"järjekord"', 'event_class': 'STATE'}]),
EnvelopingSpan(['maksan'], [{'event_ID': 'e94', 'expression': '"maksan"', 'event_class': 'OCCURRENCE'}])])

In [79]:
article_text.gold_timex_phrases

Layer(name='gold_timex_phrases', attributes=('timex_ID', 'expression', 'type', 'value'), spans=SL[EnvelopingSpan(['20.11.2002'], [{'timex_ID': 't1', 'expression': '"20.11.2002"', 'type': 'DATE', 'value': '2002-11-20'}]),
EnvelopingSpan(['aastaid'], [{'timex_ID': 't2', 'expression': '"aastaid"', 'type': 'DURATION', 'value': 'PXY'}]),
EnvelopingSpan(['kuude', 'kaupa'], [{'timex_ID': 't3', 'expression': '"kuude kaupa"', 'type': 'DURATION', 'value': 'PXM'}]),
EnvelopingSpan(['seitse', 'kuud'], [{'timex_ID': 't4', 'expression': '"seitse kuud"', 'type': 'DURATION', 'value': 'P7M'}]),
EnvelopingSpan(['kuude', 'kaupa'], [{'timex_ID': 't5', 'expression': '"kuude kaupa"', 'type': 'DURATION', 'value': 'PXM'}]),
EnvelopingSpan(['varem'], [{'timex_ID': 't6', 'expression': '"varem"', 'type': 'DATE', 'value': 'PAST_REF'}]),
EnvelopingSpan(['senistest'], [{'timex_ID': 't7', 'expression': '"senistest"', 'type': 'DATE', 'value': 'PRESENT_REF'}]),
EnvelopingSpan(['kunagi'], [{'timex_ID': 't8', 'expression': '"kunagi"', 'type': 'DATE', 'value': 'PAST_REF'}]),
EnvelopingSpan(['praegu'], [{'timex_ID': 't9', 'expression': '"praegu"', 'type': 'DATE', 'value': 'PRESENT_REF'}]),
EnvelopingSpan(['kunagi'], [{'timex_ID': 't10', 'expression': '"kunagi"', 'type': 'DATE', 'value': 'PAST_REF'}]),
EnvelopingSpan(['tänases'], [{'timex_ID': 't11', 'expression': '"tänases"', 'type': 'DATE', 'value': 'PRESENT_REF'}]),
EnvelopingSpan(['ühel', 'heal', 'päeval'], [{'timex_ID': 't12', 'expression': '"ühel heal päeval"', 'type': 'DATE', 'value': 'XXXX-XX-XX'}])])

### Relation layers

In [80]:
from estnltk_core import RelationLayer

In [81]:
event_timex_relations = load_relation_annotation(tlinkEventTimexFile)

In [82]:
rels = event_timex_relations.get('aja_ml_2002_47.tasak.a023.sol')

In [83]:
rels

{'e41': [['e41', 'IS_INCLUDED', 't6', '']],
 't6': [['e41', 'IS_INCLUDED', 't6', '']],
 'e42': [['e42', 'IS_INCLUDED', 't7', '']],
 't7': [['e42', 'IS_INCLUDED', 't7', '']],
 'e49': [['e49', 'IS_INCLUDED', 't8', '']],
 't8': [['e49', 'IS_INCLUDED', 't8', '']],
 'e71': [['e71', 'IS_INCLUDED', 't10', '']],
 't10': [['e71', 'IS_INCLUDED', 't10', '']],
 'e89': [['e89', 'IS_INCLUDED', 't12', '']],
 't12': [['e89', 'IS_INCLUDED', 't12', '']],
 'e16': [['e16', 'SIMULTANEOUS', 't4', '']],
 't4': [['e16', 'SIMULTANEOUS', 't4', '']],
 'e23': [['e23', 'SIMULTANEOUS', 't5', '']],
 't5': [['e23', 'SIMULTANEOUS', 't5', '']],
 'e2': [['e2', 'SIMULTANEOUS', 't2', '']],
 't2': [['e2', 'SIMULTANEOUS', 't2', '']],
 'e60': [['e60', 'SIMULTANEOUS', 't9', '']],
 't9': [['e60', 'SIMULTANEOUS', 't9', '']],
 'e8': [['e8', 'SIMULTANEOUS', 't3', '']],
 't3': [['e8', 'SIMULTANEOUS', 't3', '']]}

In [84]:
def create_event_timex_rel_layer(article_text, relations):
    tlinks_layer = RelationLayer('event_timex_tlinks', span_names=['a_text', 'b_text'], 
                                 attributes=['a_ID', 'rel_type', 'b_ID', 'comment'], 
                                 display_order=['a_text', 'a_ID', 'rel_type', 'b_text', 'b_ID', 'comment'], 
                                 text_object=article_text, enveloping='words')
    
    last_ann = None
    
    for entity in relations:
        ann = relations.get(entity)[0]
        
        if last_ann==ann:
            last_ann == None
            continue 
            
        else:
            last_ann = ann
            a_ID = ann[0]
            rel_type = ann[1]
            b_ID = ann[2]
            comment = ann[3]
            
            a_event = [e for e in article_text.gold_event_phrases if e['event_ID'][0]==a_ID]
            b_event = [e for e in article_text.gold_event_phrases if e['event_ID'][0]==b_ID]
            
            if a_event:
                b_timex = [t for t in article_text.gold_timex_phrases if t['timex_ID'][0]==b_ID]
                a_spans = [span.base_span for span in a_event[0]]
                b_spans = [span.base_span for span in b_timex[0]]
                
                tlinks_layer.add_annotation(a_text=a_spans, a_ID=a_ID, rel_type=rel_type,
                                            b_text=b_spans, b_ID=b_ID, comment=comment)
                
            elif b_event:
                a_timex = [t for t in article_text.gold_timex_phrases if t['timex_ID'][0]==a_ID]
                a_spans = [span.base_span for span in a_timex[0]]
                b_spans = [span.base_span for span in b_event[0]]
                
                tlinks_layer.add_annotation(a_text=a_spans, a_ID=a_ID, rel_type=rel_type,
                                            b_text=b_spans, b_ID=b_ID, comment=comment)
                
    return tlinks_layer

In [85]:
tlinks = create_event_timex_rel_layer(article_text, event_timex_relations.get('aja_ml_2002_47.tasak.a023.sol'))

In [86]:
article_text = add_layers_to_text('aja_ml_2002_47.tasak.a023.sol', article_text, articlesDCT, 
                                  [tlinks])

In [87]:
article_text

Text(text='20.11.2002 Juba aastaid on piimavarumisel kestnud anarhia . Kui vahepeal tundubki , et suuremad hädad hakkavad mööda saama , tuleb uus löök . See , et Rapla Dairy on lehmapidajatele kuude kaupa võlgu , pälvis laiemat tähelepanu alles siis , kui riik tahtis firmat juhtivale Afganistani eruohvitserile Jaqub Haidaryle eriliste teenete eest kodakondsuse kinkida . Mure suuruse võtab oma ilmekas lihtsuses kokku põllumajandusministeeriumile saadetud abipalve . Selle kirjutasid kaheksa Noarootsi lehmapidajat , kel piimaraha seitse kuud saamata . Kirjas seisab : " Võimaluse piires palume tasuta abi juristi või advokaadi näol , kes tunneks seadusi ja oskaks meid , vaeseid piimatootjaid , kaitsta . " Mida kuude kaupa saamata piimaraha tähendab , pole vaja seletada maainimesele , kellele see on üks põhilisi elatusallikaid . Mis kõige hullem - need inimesed on oma murega sisuliselt üksi , sest need , kes peaksid abi pakkuma , leiavad alati tuhat põhjendust , miks aidata pole võimalik . Põllumajandusministeerium püüab lahendusi otsida piimasektorile kiiranalüüsi tehes . Tekib küsimus , kas ülevaadet piimanduses toimuvast siis ministeeriumil varem polnudki . Kas senistest probleemidest pole õpitud ? Ja kas see hinnang tuleb ikka objektiivne või püütakse seisu euroläbirääkimiste taustal ilustada . Teised piimatööstused vaevalt Dairyt ja tema eelkäijat Lactot , kes kunagi sundis neid kokkuostuhinda kergitama , taga nutavad . Üks konkurent vähem . Pank muretseb jälle , kuidas oma laenu tagasi saada . Peaminister leiab , et rahaline abi raskustes firmadele on raiskamine . Aga maal oodatakse ja oodatakse piimaraha . Kuigi praegu töötatakse välja skeemi Dairy võlgade katmiseks , ei saa Dairyt vaadata ainult üksikjuhtumina . Kogu süsteem lonkab , ainult ei jõuta kokkuleppele , kumb jalg on haige või on tegu hoopis psüühikahäirega . Teistes , arenenumates riikides , kuuluvad piimatööstused enamasti ühistutele , mis on tootjate endi omad . Meil kunagi õitsval järjel olnud ühistegevust pole aga riik piisavalt toetada tahtnud . Et suuremad ärid õitseksid ja raha liiga laiali ei pudeneks . Ühe või paari lehma pidamine tundub selle kõrval ju nii tühine . Ent asi pole mitte lehmades , vaid inimestes . Kui asja kas või puhtmajanduslikult võtta , siis kumb on otstarbekam : kas maksta vaesematele maainimestele näljapajukit sotsiaaltoetuste näol või anda neile võimalus ise toime tulla . Läbi töö , mida nad oskavad ja austavad . Ka ilmset ebaõiglust võetakse tänases Eestis järjest enam loomuliku nähtusena . Nii ei jäägi talumehel ühel heal päeval muud üle , kui viimane lehm käekõrvale võtta ja advokaadi ukse taha viia . Piimaraha saamata , tapamajas järjekord , maksan natuuras .')

In [88]:
article_text['event_timex_tlinks']

RelationLayer(name='event_timex_tlinks', span_names=('a_text', 'b_text'), attributes=('a_ID', 'rel_type', 'b_ID', 'comment'), relations=[Relation([NamedSpan(a_text: ['ülevaadet', 'polnudki']), NamedSpan(b_text: ['varem'])], [{'a_ID': 'e41', 'rel_type': 'IS_INCLUDED', 'b_ID': 't6', 'comment': ''}]), Relation([NamedSpan(a_text: ['probleemidest']), NamedSpan(b_text: ['senistest'])], [{'a_ID': 'e42', 'rel_type': 'IS_INCLUDED', 'b_ID': 't7', 'comment': ''}]), Relation([NamedSpan(a_text: ['sundis']), NamedSpan(b_text: ['kunagi'])], [{'a_ID': 'e49', 'rel_type': 'IS_INCLUDED', 'b_ID': 't8', 'comment': ''}]), Relation([NamedSpan(a_text: ['olnud']), NamedSpan(b_text: ['kunagi'])], [{'a_ID': 'e71', 'rel_type': 'IS_INCLUDED', 'b_ID': 't10', 'comment': ''}]), Relation([NamedSpan(a_text: ['jäägi']), NamedSpan(b_text: ['ühel', 'heal', 'päeval'])], [{'a_ID': 'e89', 'rel_type': 'IS_INCLUDED', 'b_ID': 't12', 'comment': ''}]), Relation([NamedSpan(a_text: ['saamata']), NamedSpan(b_text: ['seitse', 'kuud'])], [{'a_ID': 'e16', 'rel_type': 'SIMULTANEOUS', 'b_ID': 't4', 'comment': ''}]), Relation([NamedSpan(a_text: ['saamata']), NamedSpan(b_text: ['kuude', 'kaupa'])], [{'a_ID': 'e23', 'rel_type': 'SIMULTANEOUS', 'b_ID': 't5', 'comment': ''}]), Relation([NamedSpan(a_text: ['kestnud']), NamedSpan(b_text: ['aastaid'])], [{'a_ID': 'e2', 'rel_type': 'SIMULTANEOUS', 'b_ID': 't2', 'comment': ''}]), Relation([NamedSpan(a_text: ['töötatakse']), NamedSpan(b_text: ['praegu'])], [{'a_ID': 'e60', 'rel_type': 'SIMULTANEOUS', 'b_ID': 't9', 'comment': ''}]), Relation([NamedSpan(a_text: ['on', 'võlgu']), NamedSpan(b_text: ['kuude', 'kaupa'])], [{'a_ID': 'e8', 'rel_type': 'SIMULTANEOUS', 'b_ID': 't3', 'comment': ''}])])

In [89]:
event_dct_relations = load_relation_to_dct_annotations(tlinkEventDCTFile)

In [90]:
dct_rels = event_dct_relations.get('aja_ml_2002_47.tasak.a023.sol')

In [91]:
dct_rels

{'e36': [['e36', 'AFTER', 't0', '']],
 'e44': [['e44', 'AFTER', 't0', '']],
 'e45': [['e45', 'AFTER', 't0', '']],
 'e46': [['e46', 'AFTER', 't0', '']],
 'e48': [['e48', 'AFTER', 't0', '']],
 'e54': [['e54', 'AFTER', 't0', '']],
 'e16': [['e16', 'BEFORE', 't0', '']],
 'e18': [['e18', 'BEFORE', 't0', '']],
 'e19': [['e19', 'AFTER', 't0', '']],
 'e23': [['e23', 'BEFORE', 't0', '']],
 'e2': [['e2', 'BEFORE', 't0', '']],
 'e3': [['e3', 'BEFORE', 't0', '']],
 'e42': [['e42', 'BEFORE', 't0', '']],
 'e43': [['e43', 'BEFORE', 't0', '']],
 'e74': [['e74', 'BEFORE', 't0', '']],
 'e10': [['e10', 'BEFORE', 't0', '']],
 'e11': [['e11', 'BEFORE', 't0', '']],
 'e12': [['e12', 'BEFORE', 't0', '']],
 'e14': [['e14', 'BEFORE', 't0', '']],
 'e15': [['e15', 'BEFORE', 't0', '']],
 'e41': [['e41', 'BEFORE', 't0', '']],
 'e49': [['e49', 'BEFORE', 't0', '']],
 'e50': [['e50', 'BEFORE', 't0', '']],
 'e71': [['e71', 'BEFORE', 't0', '']],
 'e72': [['e72', 'BEFORE', 't0', '']],
 'e73': [['e73', 'BEFORE', 't0', '']],
 'e9': [['e9', 'BEFORE', 't0', '']],
 'e13': [['e13', 'INCLUDES', 't0', '']],
 'e17': [['e17', 'INCLUDES', 't0', '']],
 'e1': [['e1', 'INCLUDES', 't0', '']],
 'e20': [['e20', 'INCLUDES', 't0', '']],
 'e21': [['e21', 'INCLUDES', 't0', '']],
 'e22': [['e22', 'INCLUDES', 't0', '']],
 'e27': [['e27', 'INCLUDES', 't0', '']],
 'e28': [['e28', 'INCLUDES', 't0', '']],
 'e35': [['e35', 'INCLUDES', 't0', '']],
 'e39': [['e39', 'INCLUDES', 't0', '']],
 'e40': [['e40', 'INCLUDES', 't0', '']],
 'e47': [['e47', 'INCLUDES', 't0', '']],
 'e51': [['e51', 'INCLUDES', 't0', '']],
 'e52': [['e52', 'INCLUDES', 't0', '']],
 'e53': [['e53', 'INCLUDES', 't0', '']],
 'e55': [['e55', 'INCLUDES', 't0', '']],
 'e58': [['e58', 'INCLUDES', 't0', '']],
 'e59': [['e59', 'INCLUDES', 't0', '']],
 'e60': [['e60', 'INCLUDES', 't0', '']],
 'e62': [['e62', 'INCLUDES', 't0', '']],
 'e63': [['e63', 'INCLUDES', 't0', '']],
 'e64': [['e64', 'INCLUDES', 't0', '']],
 'e65': [['e65', 'INCLUDES', 't0', '']],
 'e69': [['e69', 'INCLUDES', 't0', '']],
 'e70': [['e70', 'INCLUDES', 't0', '']],
 'e75': [['e75', 'INCLUDES', 't0', '']],
 'e76': [['e76', 'INCLUDES', 't0', '']],
 'e77': [['e77', 'INCLUDES', 't0', '']],
 'e78': [['e78', 'INCLUDES', 't0', '']],
 'e79': [['e79', 'INCLUDES', 't0', '']],
 'e7': [['e7', 'INCLUDES', 't0', '']],
 'e88': [['e88', 'INCLUDES', 't0', '']],
 'e8': [['e8', 'INCLUDES', 't0', '']],
 'e37': [['e37', 'AFTER', 't0', '']],
 'e38': [['e38', 'AFTER', 't0', '']],
 'e61': [['e61', 'AFTER', 't0', '']],
 'e24': [['e24', 'VAGUE', 't0', '']],
 'e25': [['e25', 'VAGUE', 't0', '']],
 'e26': [['e26', 'VAGUE', 't0', '']],
 'e29': [['e29', 'VAGUE', 't0', '']],
 'e30': [['e30', 'VAGUE', 't0', '']],
 'e31': [['e31', 'VAGUE', 't0', '']],
 'e32': [['e32', 'VAGUE', 't0', '']],
 'e33': [['e33', 'VAGUE', 't0', '']],
 'e34': [['e34', 'VAGUE', 't0', '']],
 'e4': [['e4', 'VAGUE', 't0', '']],
 'e56': [['e56', 'VAGUE', 't0', '']],
 'e57': [['e57', 'VAGUE', 't0', '']],
 'e5': [['e5', 'VAGUE', 't0', '']],
 'e66': [['e66', 'VAGUE', 't0', '']],
 'e67': [['e67', 'VAGUE', 't0', '']],
 'e68': [['e68', 'VAGUE', 't0', '']],
 'e6': [['e6', 'VAGUE', 't0', '']],
 'e80': [['e80', 'VAGUE', 't0', '']],
 'e81': [['e81', 'VAGUE', 't0', '']],
 'e82': [['e82', 'VAGUE', 't0', '']],
 'e83': [['e83', 'VAGUE', 't0', '']],
 'e84': [['e84', 'VAGUE', 't0', '']],
 'e85': [['e85', 'VAGUE', 't0', '']],
 'e86': [['e86', 'VAGUE', 't0', '']],
 'e87': [['e87', 'VAGUE', 't0', '']],
 'e89': [['e89', 'VAGUE', 't0', '']],
 'e90': [['e90', 'VAGUE', 't0', '']],
 'e91': [['e91', 'VAGUE', 't0', '']],
 'e92': [['e92', 'VAGUE', 't0', '']],
 'e93': [['e93', 'VAGUE', 't0', '']],
 'e94': [['e94', 'VAGUE', 't0', '']]}

In [93]:
baseAnnotations = load_base_segmentation(baseAnnotationFile)
(eventsByLoc, eventsByID) = load_entity_annotation(eventAnnotationFile)
articlesDCT = load_articles_DCT(articleMetadata_file)
(timexesByLoc, timexesByID) = load_entity_annotation(timexAnnotationFile)

In [104]:
for filename in articlesDCT.keys():
    article_text, mapping = create_Text_object(filename, articlesDCT, baseAnnotations, eventsByLoc, timexesByLoc)
    
    if 'functionInDocument="CREATION_TIME"' in article_text.gold_timexes['timex_annotation'][0][0]:
        print(f'{filename}, {article_text.gold_timexes[0]}')
        print()
        print()
    else:
        print(f'{filename}, {article_text.gold_timexes[0]}, {" ".join(article_text.sentences[0].text)}')
        print()
        print()

aja_ml_2002_47.tasak.a006.sol, Span('2004.', [{'corpus_sentence_ID': 2, 'corpus_word_ID': 8, 'timex_ID': 't1', 'expression': '"2004. aasta maiks"', 'timex_annotation': 'TIMEX DATE 2004-05 multiword="true"', 'type': 'DATE', 'value': '2004-05'}]), 20.11.2002 Tallinna Sadam ehitab Saaremaa süvasadama Küdema lahe läänerannikule endisesse Tamme sadamakohta Mustjala valda .


aja_ml_2002_47.tasak.a007.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a008.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a014.sol, Span('21.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"21.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-21 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-21'}])


aja_ml_2002_47.tasak.a016.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a017.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a023.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a025.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a028.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a030.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a031.sol, Span('praegu', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 2, 'timex_ID': 't1', 'expression': '"praegu"', 'timex_annotation': 'TIMEX DATE PRESENT_REF', 'type': 'DATE', 'value': 'PRESENT_REF'}]), 20.11.2002 Turgudel valitseb praegu suur vaikus enne jõulueelset tungi .


aja_ml_2002_47.tasak.a033.sol, Span('iga', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 6, 'timex_ID': 't1', 'expression': '"iga kuu"', 'timex_annotation': 'TIMEX SET P1M quant="EVERY" comment="fraas: iga kuu esimesel kolmapäeval" multiword="true"', 'type': 'SET', 'value': 'P1M'}]), Tampere vanaautode klubi liikmed saavad kokku iga kuu esimesel kolmapäeval .


aja_ml_2002_47.tasak.a038.sol, Span('Kuuendat', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"Kuuendat aastat"', 'timex_annotation': 'TIMEX DURATION P6Y comment="value vaieldav, ka: XXXX" multiword="true"', 'type': 'DURATION', 'value': 'P6Y'}]), Kuuendat aastat peetava Pimedate Ööde Filmifestivali ( PÖFF ) juhatab kolmandat korda sisse tudengifilmide festival , seekord 23. - 29. novembrini Kinomajas .


aja_ml_2002_47.tasak.a040.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a041.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a042.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a045.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_ml_2002_47.tasak.a051.sol, Span('20.11.2002', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"20.11.2002"', 'timex_annotation': 'TIMEX DATE 2002-11-20 functionInDocument="CREATION_TIME"', 'type': 'DATE', 'value': '2002-11-20'}])


aja_pm_2000_10_04.tasak.a001.sol, Span('varem', [{'corpus_sentence_ID': 2, 'corpus_word_ID': 13, 'timex_ID': 't1', 'expression': '"varem"', 'timex_annotation': 'TIMEX DATE PAST_REF', 'type': 'DATE', 'value': 'PAST_REF'}]), Põllumajandusülikoolis on tekitanud ärevust haridusministeeriumi kava jagada kool kaheks : luua tehnikaalade põhjal Tartusse uus rakenduslik kõrgkool ja liita ülejäänud erialad Tartu Ülikooliga .


aja_pm_2000_10_04.tasak.a003.sol, Span('kolmandat', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 7, 'timex_ID': 't1', 'expression': '"kolmandat päeva"', 'timex_annotation': 'TIMEX DATE XXXX-XX-XX comment="fraas: kolmandat päeva põlevat" multiword="true"', 'type': 'DATE', 'value': 'XXXX-XX-XX'}]), Rannu valla servas Väike-Rakkes kustutavad pritsimehed juba kolmandat päeva põlevat tuhandet tonni briketti , selle omanik Sangla Turvas kahtlustab süütamist .


aja_pm_2000_10_04.tasak.a004.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 3, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Tartu linnavalitsus tunnistas eile bussifirma Liikor erastamise nurjunuks , kuid ei otsustanud ettevõtte saatust .


aja_pm_2000_10_04.tasak.a006.sol, Span('sel', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 5, 'timex_ID': 't1', 'expression': '"sel sügisel"', 'timex_annotation': 'TIMEX DATE 2000-FA multiword="true"', 'type': 'DATE', 'value': '2000-FA'}]), Tartu majaomanikud ei pääse ka sel sügisel lehtede riisumisest nende krundiga piirnevalt linna maalt , samuti talvel lume rookimisest linna kõnniteedelt , sest volikogu ei täitnud õiguskantsleri nõuet muuta heakorraeeskirja .


aja_pm_2000_10_04.tasak.a007.sol, Span('tänavu', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 8, 'timex_ID': 't1', 'expression': '"tänavu"', 'timex_annotation': 'TIMEX DATE 2000', 'type': 'DATE', 'value': '2000'}]), Tartu ja maakonna ligi 3500 telefonitaotlejast saab veel tänavu Eesti Telefoni kliendiks paar-kolmsada ootajat .


aja_pm_2000_10_04.tasak.a009.sol, Span('igal', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 6, 'timex_ID': 't1', 'expression': '"igal nädalal"', 'timex_annotation': 'TIMEX SET XXXX-WXX quant="EVERY" multiword="true"', 'type': 'SET', 'value': 'XXXX-WXX'}]), Aidsipuhang Narvas ehmatas ka tartlasi - kitsukese aidsikabineti ukse taha tekkis isegi järjekord , kuid ühtki HIV-positiivset testitute hulgas polnud .


aja_pm_2000_10_04.tasak.a010.sol, Span('oktoobri', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 19, 'timex_ID': 't1', 'expression': '"oktoobri lõpus"', 'timex_annotation': 'TIMEX DATE 2000-10 mod="END" multiword="true"', 'type': 'DATE', 'value': '2000-10'}]), Ehitusettevõtja Rašid Šabanov , kes kavatseb 2000 dollariga taskus seigelda Austraaliasse ja tagasi , otsib endale reisikaaslasi .


aja_pm_2000_10_04.tasak.a012.sol, Span('Täna', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"Täna"', 'timex_annotation': 'TIMEX DATE 2000-10-04', 'type': 'DATE', 'value': '2000-10-04'}]), Täna alustavad hooaega korvpallinaiskonnad .


aja_pm_2000_10_04.tasak.a013.sol, Span('tänavu', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 6, 'timex_ID': 't1', 'expression': '"tänavu"', 'timex_annotation': 'TIMEX DATE 2000', 'type': 'DATE', 'value': '2000'}]), Traditsioonilise Gunnar Uusi mälestusvõistluse põhiturniiril osales tänavu 36 mängijat .

aja_pm_2000_10_04.tasak.a015.sol, Span('praeguse', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 17, 'timex_ID': 't1', 'expression': '"praeguse"', 'timex_annotation': 'TIMEX DATE PRESENT_REF comment="fraas: praeguse ülikooli peahoone esisel alal"', 'type': 'DATE', 'value': 'PRESENT_REF'}]), Ene-Lille Jaansoni kinnitusel eksivad need , kes on väitnud , et Tartu ülikooli trükikoda alustas tööd puumajas praeguse ülikooli peahoone esisel alal .


aja_pm_2000_10_04.tasak.a016.sol, Span('Laupäeva', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"Laupäeva õhtul kell 23"', 'timex_annotation': 'TIMEX TIME 2000-09-30T23 multiword="true"', 'type': 'TIME', 'value': '2000-09-30T23'}]), Nooruk sai peksa ja jäi varast ilma Laupäeva õhtul kell 23 teatati politseisse , et raudteejaama lähedal pargis olid kolm noormeest Kastani bussipeatuses läinud kallale 17-aastase noorukile .


aja_pm_2000_10_04.tasak.a018.sol, Span('Tollane', [{'corpus_sentence_ID': 6, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"Tollane"', 'timex_annotation': 'TIMEX DATE PAST_REF', 'type': 'DATE', 'value': 'PAST_REF'}]), Eelmistel olümpiamängudel läks eestlastel kehvasti .


aja_pm_2000_10_04.tasak.a019.sol, Span('praegu', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 11, 'timex_ID': 't1', 'expression': '"praegu"', 'timex_annotation': 'TIMEX DATE PRESENT_REF', 'type': 'DATE', 'value': 'PRESENT_REF'}]), Peaministrihärra Mart Laari kinnitusel pole valitsusel plaanis pensione külmutada , vaid praegu tegeldakse sellega , kuidas üle minna pensionide indekseeritud maksmisele .


aja_pm_2000_10_04.tasak.a021.sol, Span('Tänavu', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"Tänavu"', 'timex_annotation': 'TIMEX DATE 2000', 'type': 'DATE', 'value': '2000'}]), Tänavu istus Tartu Ülikoolis lisaks 15 riigieelarvelisele kohale koolipinki poolteist korda rohkem tasulistel kohtadel suhtekorraldusharidust nõutavaid noori inimesi , avatud ülikoolis veel samapalju .


aja_pm_2000_10_04.tasak.a023.sol, Span('eile', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 4, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Raskesse rahalisse seisu sattunud vallad ja väikelinnad paluvad valitsuselt kriisiabiks miljoneid kroone Tootsi väikeasula õpilased pidid eile hämara söökla lõunalauas leppima vaid võileibadega , sest võlapöörisesse kukkunud vald ei suuda enam maksta kooli ja lasteaia elektri ja kütte eest .


aja_pm_2000_10_04.tasak.a025.sol, Span('sel', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 12, 'timex_ID': 't1', 'expression': '"sel aastal"', 'timex_annotation': 'TIMEX DATE 2000 multiword="true"', 'type': 'DATE', 'value': '2000'}]), Valdade tugevdamine haldusterritoriaalse reformi abil on vältimatu Paljude valdade ja väikelinnade eelarve peamine allikas - üksikisiku tulumaks - jääb sel aastal loodetust märksa väiksemaks ning küsimärgi alla satub kohaliku elu normaalne jätkumine .


aja_pm_2000_10_04.tasak.a028.sol, Span('üle', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 9, 'timex_ID': 't1', 'expression': '"üle kahe nädala"', 'timex_annotation': 'TIMEX DURATION P2W mod="MORE_THAN" multiword="true"', 'type': 'DURATION', 'value': 'P2W'}]), Nobelistist kirjaniku Samuel Becketti nime seostatakse enamasti Iiri- või Prantsusmaaga .


aja_pm_2000_10_04.tasak.a029.sol, Span('1992.', [{'corpus_sentence_ID': 3, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"1992. aastal"', 'timex_annotation': 'TIMEX DATE 1992 multiword="true"', 'type': 'DATE', 'value': '1992'}]), Eesti showtrupp võitis Venemaa telekonkursil esikoha Tallinna Lindakivi kultuurikeskuse show-trupp IRIS on võitnud Moskvas rahvusvahelisel telekonkursil " Utrennaja svezda " ( " Hommikutäht " ) vokaalansamblite arvestuses esikoha .


aja_pm_2000_10_04.tasak.a030.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 2, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Valitsus otsustas eile hoolimata segastest maaküsimustest panna 250 miljoni kroonise alghinnaga müüki AS Tallinna Olümpiapurjespordikeskuse ( TOP ) kogu aktsiapaki .


aja_pm_2000_10_04.tasak.a031.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 1, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Valitsuses eile vastu võetud määruse kohaselt on edaspidi lubatud eriotstarbelise kütteõli müümine põllumeestele ja kaluritele kõikides tanklates .


aja_pm_2000_10_04.tasak.a033.sol, Span('eelmisel', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 5, 'timex_ID': 't1', 'expression': '"eelmisel kuul"', 'timex_annotation': 'TIMEX DATE 2000-09 multiword="true"', 'type': 'DATE', 'value': '2000-09'}]), Diilerivahetuse tõttu ei müüdud Eestis eelmisel kuul ühtegi Fordi .


aja_pm_2000_10_04.tasak.a034.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 4, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Nõudluse pidev suurenemine viis eile EVP hinna börsil 65 sendini , kuuga on hind kerkinud juba 15 sendi ehk ligi kolmandiku võrra .


aja_pm_2000_10_04.tasak.a041.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 2, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Valitsus tegi eile poliitilise otsuse ehitada kunstimuuseumi uus hoone Kadriorgu hoolimata sellest , et nii jäävad sobilikust asupaigast ilma sõjaväeluurajad ja Tallinna linnavõim pooldas muuseumimaja hoopis kesklinna .


aja_pm_2000_10_04.tasak.a042.sol, Span('täna', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 2, 'timex_ID': 't1', 'expression': '"täna"', 'timex_annotation': 'TIMEX DATE 2000-10-04', 'type': 'DATE', 'value': '2000-10-04'}]), Keskkriminaalpolitsei loodab täna esitada süüdistused Tallinna Keskturu direktori Vadim Polishtshuki väidetavatele ihukaitsjatele , keda kahtlustatakse ärimees Mait Metsamaa palgamõrva tellimise vahendamises .


aja_pm_2000_10_04.tasak.a044.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 8, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Kuigi Haabersti linnaosa endine peaarhitekt Riho Hürden oli eile valmis Tallinna linnakohtust lahkuma kas süütu või süüdlasena , jäi ta mõlemast tiitlist ilma , sest kohus saatis ta kriminaalasja kaitsepolitseisse täiendavale eeluurimisele .


aja_pm_2000_10_04.tasak.a045.sol, Span('üleeile', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 4, 'timex_ID': 't1', 'expression': '"üleeile õhtul"', 'timex_annotation': 'TIMEX TIME 2000-10-02TEV multiword="true"', 'type': 'TIME', 'value': '2000-10-02TEV'}]), Pärnu linnavolikogu Reformierakonna fraktsioon teeb võimuliidukaaslasele Isamaaliidule ettepaneku anda haridust ja kultuuri juhtiva abilinnapea koht Reformierakonnale , ütles Reformierakonna Pärnu piirkonna esimees Väino Linde .


aja_pm_2000_10_04.tasak.a046.sol, Span('tuleval', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 6, 'timex_ID': 't1', 'expression': '"tuleval nädalal"', 'timex_annotation': 'TIMEX DATE 2000-W41 multiword="true"', 'type': 'DATE', 'value': '2000-W41'}]), Endisesse tootmishoonesse tuleb hokimängijate , iluuisutajate ja tavaliste uisutajate jaoks kolm jääplatsi Tallinnas Lasnamäel endises Dvigateli tootmishoones avab tuleval nädalal uksed pealinna teine jäähall , mille katuse all hakkab korraga töös olema kolm jääplatsi .


aja_pm_2000_10_04.tasak.a047.sol, Span('selle', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 17, 'timex_ID': 't1', 'expression': '"selle kuu lõpuks"', 'timex_annotation': 'TIMEX DATE 2000-10 mod="END" multiword="true"', 'type': 'DATE', 'value': '2000-10'}]), Hundipea sadamas jäämurdja Tarmo naabruses oma saatust ootav muuseumilaev Suur Tõll võib uude koju Admiraliteedi basseinis jõuda selle kuu lõpuks , kuid alles siis , kui vajalik kokkulepe Tallinna Sadama ja Eesti Meremuuseumi vahel saab sõlmitud .


aja_pm_2000_10_04.tasak.a050.sol, Span('täna', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 5, 'timex_ID': 't1', 'expression': '"täna"', 'timex_annotation': 'TIMEX DATE 2000-10-04', 'type': 'DATE', 'value': '2000-10-04'}]), USA loodab , et uus konflikt näitab pooltele veel kord rahu alternatiive USA välisminister Madelein Albright kohtub täna Pariisis Iisraeli peaministri Ehud Baraki ja palestiinlaste liidri Yasser Arafatiga , püüdes lõpetada Lähis-Idas taas puhkenud vägivalda .


aja_pm_2000_10_04.tasak.a051.sol, Span('eile', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 5, 'timex_ID': 't1', 'expression': '"eile"', 'timex_annotation': 'TIMEX DATE 2000-10-03', 'type': 'DATE', 'value': '2000-10-03'}]), Venemaa president Vladimir Putin alustas eile India-visiiti , millega loodab pisut taastada kahe riigi vaheliste suhete külma sõja aegset tihedust .

aja_pm_2000_10_04.tasak.a052.sol, Span('sel', [{'corpus_sentence_ID': 1, 'corpus_word_ID': 17, 'timex_ID': 't1', 'expression': '"sel viivul"', 'timex_annotation': 'TIMEX DATE PAST_REF multiword="true"', 'type': 'DATE', 'value': 'PAST_REF'}]), Ajakirjanikud lausa kiskusid õblukese blondi naise autost välja .


aja_pm_2000_10_04.tasak.a053.sol, Span('seniseid', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 10, 'timex_ID': 't1', 'expression': '"seniseid"', 'timex_annotation': 'TIMEX DATE PRESENT_REF', 'type': 'DATE', 'value': 'PRESENT_REF'}]), Saksamaa ühinemise kümnenda aastapäeva pidustustele saabunud välismaised poliitikud tunnustasid riigi seniseid saavutusi , ent hoiatasid Saksa riigijuhte maal leviva paremäärmusluse ja korralageduse eest .


aja_pm_2000_10_04.tasak.a054.sol, Span('teisel', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 4, 'timex_ID': 't1', 'expression': '"teisel päeval"', 'timex_annotation': 'TIMEX DATE 2000-XX-XX comment="seotud fraas: üldstreigi teisel päeval" multiword="true"', 'type': 'DATE', 'value': '2000-XX-XX'}]), Jugoslaavia opositsioon jätkab üldstreigi teisel päeval inimeste kutsumist tänavatele , et sundida president Slobodan Milosevici tagasi astuma .


aja_pm_2000_10_04.tasak.a055.sol, Span('iga-aastasel', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 4, 'timex_ID': 't1', 'expression': '"iga-aastasel"', 'timex_annotation': 'TIMEX SET P1Y quant="EVERY"', 'type': 'SET', 'value': 'P1Y'}]), Lõuna-Inglismaa kuurortlinnas Bournemouthis alanud iga-aastasel konservatiivide parteikonverentsil on tähelepanu keskpunkti tõstetud veidi üllatuslikult tervishoiupoliitika , vähem üllatuslikult aga ELi temaatika .


aja_pm_2000_10_04.tasak.a056.sol, Span('kell', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 2, 'timex_ID': 't1', 'expression': '"kell 20.05"', 'timex_annotation': 'TIMEX TIME T20:05 multiword="true"', 'type': 'TIME', 'value': 'T20:05'}]), ETV , kell 20.05 , " Pealtnägija " .


aja_pm_2000_10_04.tasak.a058.sol, Span('60ndatel', [{'corpus_sentence_ID': 4, 'corpus_word_ID': 4, 'timex_ID': 't1', 'expression': '"60ndatel aastatel"', 'timex_annotation': 'TIMEX DATE 196 multiword="true"', 'type': 'DATE', 'value': '196'}]), Susan Sarandon on suutnud teha karjääri Hollywoodi tavasid eirates .


aja_sloleht_2007_12_17.tasak.a001.sol, Span('2009.', [{'corpus_sentence_ID': 0, 'corpus_word_ID': 0, 'timex_ID': 't1', 'expression': '"2009. aastast"', 'timex_annotation': 'TIMEX DATE 2009 multiword="true"', 'type': 'DATE', 'value': '2009'}]), 2009. aastast tuleb Saksamaal kõik majad soojustada nii , et kütteks kuluks energiat 30% vähem kui praegu , teatas minister Wolfgang Tiefensee .

IndexError: list index out of range

### Running pipeline on all EstTimeML corpus articles

In [2]:
baseAnnotations = load_base_segmentation(baseAnnotationFile)
(eventsByLoc, eventsByID) = load_entity_annotation(eventAnnotationFile)
articlesDCT = load_articles_DCT(articleMetadata_file)
(timexesByLoc, timexesByID) = load_entity_annotation(timexAnnotationFile)

In [3]:
n_saved_articles = 0
for filename in articlesDCT.keys():
    print(filename)
    
    article_text, mapping = create_Text_object(filename, articlesDCT, baseAnnotations, eventsByLoc, timexesByLoc)
    
    gold_word_events = create_gold_word_events_layer(article_text, baseAnnotations.get(filename))
    gold_event_phrases = create_gold_event_phrases(article_text)
    gold_timex_phrases = create_gold_timex_phrases(article_text)
    
    article_text = add_layers_to_text(filename, article_text, articlesDCT, [gold_word_events, gold_event_phrases, gold_timex_phrases])
    
    # Text-object is saved to JSON file
    save_Text_to_json(article_text)
    n_saved_articles+=1
    
print()
print("Saved", n_saved_articles, "articles in JSON-format.")

aja_ml_2002_47.tasak.a006.sol
aja_ml_2002_47.tasak.a007.sol
aja_ml_2002_47.tasak.a008.sol
aja_ml_2002_47.tasak.a014.sol
aja_ml_2002_47.tasak.a016.sol
aja_ml_2002_47.tasak.a017.sol
aja_ml_2002_47.tasak.a023.sol
aja_ml_2002_47.tasak.a025.sol
aja_ml_2002_47.tasak.a028.sol
aja_ml_2002_47.tasak.a030.sol
aja_ml_2002_47.tasak.a031.sol
aja_ml_2002_47.tasak.a033.sol
aja_ml_2002_47.tasak.a038.sol
aja_ml_2002_47.tasak.a040.sol
aja_ml_2002_47.tasak.a041.sol
aja_ml_2002_47.tasak.a042.sol
aja_ml_2002_47.tasak.a045.sol
aja_ml_2002_47.tasak.a051.sol
aja_pm_2000_10_04.tasak.a001.sol
aja_pm_2000_10_04.tasak.a003.sol
aja_pm_2000_10_04.tasak.a004.sol
aja_pm_2000_10_04.tasak.a006.sol
aja_pm_2000_10_04.tasak.a007.sol
aja_pm_2000_10_04.tasak.a009.sol
aja_pm_2000_10_04.tasak.a010.sol
aja_pm_2000_10_04.tasak.a012.sol
aja_pm_2000_10_04.tasak.a013.sol
aja_pm_2000_10_04.tasak.a015.sol
aja_pm_2000_10_04.tasak.a016.sol
aja_pm_2000_10_04.tasak.a018.sol
aja_pm_2000_10_04.tasak.a019.sol
aja_pm_2000_10_04.tasak.a021.sol
aja_pm_2000_10_04.tasak.a023.sol
aja_pm_2000_10_04.tasak.a025.sol
aja_pm_2000_10_04.tasak.a028.sol
aja_pm_2000_10_04.tasak.a029.sol
aja_pm_2000_10_04.tasak.a030.sol
aja_pm_2000_10_04.tasak.a031.sol
aja_pm_2000_10_04.tasak.a033.sol
aja_pm_2000_10_04.tasak.a034.sol
aja_pm_2000_10_04.tasak.a041.sol
aja_pm_2000_10_04.tasak.a042.sol
aja_pm_2000_10_04.tasak.a044.sol
aja_pm_2000_10_04.tasak.a045.sol
aja_pm_2000_10_04.tasak.a046.sol
aja_pm_2000_10_04.tasak.a047.sol
aja_pm_2000_10_04.tasak.a050.sol
aja_pm_2000_10_04.tasak.a051.sol
aja_pm_2000_10_04.tasak.a052.sol
aja_pm_2000_10_04.tasak.a053.sol
aja_pm_2000_10_04.tasak.a054.sol
aja_pm_2000_10_04.tasak.a055.sol
aja_pm_2000_10_04.tasak.a056.sol
aja_pm_2000_10_04.tasak.a058.sol
aja_sloleht_2007_12_17.tasak.a001.sol
aja_sloleht_2007_12_17.tasak.a002.sol
aja_sloleht_2007_12_17.tasak.a003.sol
aja_sloleht_2007_12_17.tasak.a004.sol
aja_sloleht_2007_12_17.tasak.a005.sol
aja_sloleht_2007_12_17.tasak.a006.sol
aja_sloleht_2007_12_17.tasak.a009.sol
aja_sloleht_2007_12_17.tasak.a010.sol
aja_sloleht_2007_12_17.tasak.a012.sol
aja_sloleht_2007_12_17.tasak.a015.sol
aja_sloleht_2007_12_17.tasak.a016.sol
aja_sloleht_2007_12_17.tasak.a017.sol
aja_sloleht_2007_12_17.tasak.a019.sol
aja_sloleht_2007_12_17.tasak.a020.sol
aja_sloleht_2007_12_17.tasak.a022.sol
aja_sloleht_2007_12_17.tasak.a023.sol
aja_sloleht_2007_12_17.tasak.a032.sol
aja_sloleht_2007_12_17.tasak.a033.sol
aja_sloleht_2007_12_17.tasak.a037.sol
aja_sloleht_2007_12_17.tasak.a039.sol
aja_sloleht_2007_12_17.tasak.a040.sol
aja_sloleht_2007_12_17.tasak.a043.sol
aja_sloleht_2007_12_17.tasak.a044.sol
aja_sloleht_2007_12_17.tasak.a046.sol
aja_sloleht_2007_12_17.tasak.a047.sol
aja_sloleht_2007_12_17.tasak.a051.sol

Saved 80 articles in JSON-format.